#ifndef EXT4_CONFIG_H_
#define EXT4_CONFIG_H_

#define CONFIG_EXT4_BLOCKDEVS_COUNT 1
#define CONFIG_EXT4_MOUNTPOINTS_COUNT 1

#define CONFIG_EXT4_USE_USER_MALLOC 0
#define CONFIG_EXT4_MALLOC_STANDARD 1

#define CONFIG_DEBUG_PRINTF 0
#define CONFIG_DEBUG_ASSERT 0

#endif
