#ifndef EXT4_CONFIG_H_
#define EXT4_CONFIG_H_

#define CONFIG_EXT4_BLOCKDEVS_COUNT 1
#define CONFIG_EXT4_MOUNTPOINTS_COUNT 1

#define CONFIG_EXT4_MAX_MP_NAME 32
#define CONFIG_EXT4_MAX_BLOCKDEV_NAME 32
#define CONFIG_BLOCK_DEV_CACHE_SIZE 8
#define CONFIG_MAX_TRUNCATE_SIZE (16 * 1024 * 1024)

#define CONFIG_SUPPORTED_FINCOM 0xFFFFFFFF
#define CONFIG_SUPPORTED_FRO_COM 0xFFFFFFFF
#define CONFIG_SUPPORTED_FCOMPAT 0xFFFFFFFF

#define CONFIG_EXT4_USE_USER_MALLOC 0
#define CONFIG_EXT4_USE_XATTR 1
#define CONFIG_XATTR_ENABLE 1
#define CONFIG_META_CSUM_ENABLE 1
#define CONFIG_EXT4_MALLOC_STANDARD 1

#define CONFIG_DEBUG_PRINTF 0
#define CONFIG_DEBUG_ASSERT 0

#endif
